## ndarray의 연산

In [2]:
import numpy as np

In [4]:
ar=np.array([1,2,3,4,5])
br=np.array([1,2,3,4,5])
cr=np.array([1,2,3,4])
print(ar+br)
#print(ar+cr) # 브로드캐스트 연산을 하려하지만, 연산 질패를 합니다. 더할 수 없다.
print(ar+1) #얘는 ar+[1,1,1,1,1]로 브로드캐스트 연산에 성공합니다.
# 차원은 맞춰줄 수 있지만, 그 안에 있는 개수는 꼭 맞춰줘야한다.

[ 2  4  6  8 10]
[2 3 4 5 6]


In [8]:
dr=np.array([1,2,3,4])
er=np.array([1,2])
# print(dr+er) # 이건 절대 안된다 하지만?
dr.reshape((2,2))


[1 2 3 4]


In [12]:
#산술연산
ar=np.array([1,2,3,4,5])
br=np.array([10,20,30,40,50])
result=ar+br
print(result)
result=ar+4
#이는 2개의 차원이 다른 경우이다.
# 이 경우, 적은 차원의 데이터를 큰 차원으로 수정
#ar+[4,4,4,4,4]
print(result)
kr=np.array(range(1,11)) #1부터 10까지
print(kr)
# print(ar+cr) # 요소 개수가 5개, 10개 차이로 오류가 남
cr=kr.reshape((2,5)) #2행 5열로 만들기
print(cr)
print(ar+cr)

[11 22 33 44 55]
[5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [14]:
# 논리연산
ar=np.array([1,2,3,4,5])
br=np.array([10,20,30,40,50])
print(ar>br)
print(np.not_equal(ar,br))
print(np.logical_xor(ar,br)) # 다 값이 상수로 존재(true)해서 xor는 False
# and or xor는 bool(Ture, False)로 변경해서 판정함

[False False False False False]
[ True  True  True  True  True]
[False False False False False]


In [16]:
ar=np.array([1,2,3,4,5])
br=np.array([10,20,30,40,50])
ar+=br # ar=ar+br
print(ar)
# 일반 list는 * 연산은 반복이다. 배열은 진짜 곱셈이다.

[11 22 33 44 55]


In [18]:
ar=np.array([1,2,3,4,5])
br=np.array([10,20,30,40,50])
print(1 in ar)
print([1,2] in ar)
print([1,100] in ar)

True
False
False


C:\Users\USER\AppData\Local\Temp\ipykernel_20000\1456367003.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,2] in ar)
C:\Users\USER\AppData\Local\Temp\ipykernel_20000\1456367003.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,100] in ar)
